In [1]:
a = [1,'hello', 3.4, True, 2,'rash']
a.append(5)
print(a)

[1, 'hello', 3.4, True, 2, 'rash', 5]


In [3]:
import numpy as np

a = [1, 2, 3, 4]

arr = np.array(a)

print("List in python : ", a)

print("Numpy Array in python :",arr)

List in python :  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


In [4]:
import numpy as np

list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [9,10,11,12]

sample_array = np.array([list1, list2, list3])

print(sample_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
import numpy as np
sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)


In [9]:
import numpy as np
a = np.array([1, 2, 3, 4])

# Element-wise operations
print(a * 2)  

# Multi-dimensional array
res = np.array([[1, 2], [3, 4]])
print(res * 2)

[2 4 6 8]
[[2 4]
 [6 8]]


In [10]:
import array as arr
a = arr.array('i', [1, 2, 3])

# accessing First Araay
print(a[0])

# adding element to array
a.append(5)
print(a)

1
array('i', [1, 2, 3, 5])


In [13]:
import array as arr
a = arr.array('i', [1, 2, 3, 4, 5])

for i in range(0, 5):
    print(a[i])

1
2
3
4
5


In [16]:
# impor array as arr

a = arr.array('i', [1, 2, 3, 4, 5]) 
print(*a)

a.insert(2, 10)  # Insert 10 at index 2
print(*a)

1 2 3 4 5
1 2 10 3 4 5


In [17]:
import array as arr
a = arr.array('i', [1, 2, 3, 4, 5, 6])

print(a[0])
print(a[3])

b = arr.array('d', [2.5, 3.2, 3.3])
print(b[1])
print(b[2])

1
4
3.2
3.3


In [18]:
import array
a = array.array('i', [1, 2, 3, 1, 5])

# remove first occurance of 1
a.remove(1)
print(a)

# remove item at index 2
a.pop(2)
print(a)

array('i', [2, 3, 1, 5])
array('i', [2, 3, 5])


In [19]:
import array as arr
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = arr.array('i', a)

res = a[3:8]
print(res)

res = a[5:]
print(res)

res = a[:]
print(res)

[4, 5, 6, 7, 8]
[6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [20]:
import array
a = array.array('i', [1, 2, 3, 1, 2, 5])

# update item at index 2
a[2] = 6
print(a)

# update item at index 4
a[4] = 8
print(a)

array('i', [1, 2, 6, 1, 2, 5])
array('i', [1, 2, 6, 1, 8, 5])


In [22]:
import array
a = array.array('i', [1, 2, 3, 4, 2, 5, 2])

count = a.count(1)
print(count)

1


In [24]:
# import array
a = array.array('i', [1, 2, 3, 4, 5])

a.reverse()
print(*a)

5 4 3 2 1


In [25]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Shape:", arr.shape)
print("2nd row:", arr[1, :])
print("Column 0:", arr[:, 0])
print("Sum:", np.sum(arr))


Shape: (2, 3)
2nd row: [40 50 60]
Column 0: [10 40]
Sum: 210


In [26]:
import numpy as np

sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int64
Data type of array 2 : float64
